name: Gradle CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      # Build project
      - name: Build with Gradle
        run: ./gradlew build --no-daemon

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      # Run tests with coverage
      - name: Run tests
        run: ./gradlew test jacocoTestReport --no-daemon

      # Display Jacoco coverage summary
      - name: Show coverage summary
        run: |
          awk -F"," '{ instructions += $4 + $5; covered += $5 } \
            END { print covered "/" instructions " instructions covered"; \
            print 100*covered/instructions "% covered" }' \
            build/reports/jacoco/test/jacocoTestReport.csv || true

      # Upload Jacoco coverage report
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/jacocoTestReport.xml
